#!/bin/python

def spiral(N):
    matrix = [[1] * N for _ in range(N)]
    x = y = (N - 1) // 2
    direction = (0, 1) # Right
    number = 1
    repetition = 0

    while True:
        repetition += 1
        if (repetition + number > N * N):
            break

        for _ in range(2):
            dx, dy = direction
            for _ in range(repetition):
                x += dx
                y += dy
                number += 1
                matrix[x][y] = number

            direction = (dy, -dx) # Clockwise turn

    return matrix
