#!/bin/python

def spiral(N):
    matrix = [[0] * N for _ in range(N)]
    x = y = (N - 1) // 2
    direction = (0, 1) # Right
    number = 1
    repetition = 0
    matrix[x][y] = number # Fill center

    done = False
    while not done:
        repetition += 1

        for _ in range(2):
            dx, dy = direction
            for _ in range(repetition):
                number += 1
                if (number > N * N):
                    done = True
                    break
                x += dx
                y += dy
                matrix[x][y] = number

            direction = (dy, -dx) # Clockwise turn

    return matrix
